[package]
authors = ["Jade Meskill <jade.meskill@gmail.com>"]
edition = "2018"
license = "MIT"
name = "blimey"
version = "0.1.0"

[dependencies]
futures = "*"
http-types = "2.5.0"
serde = "*"
structopt = "0.3"
surf = "2.2.0"

[dependencies.async-std]
features = ["attributes"]
version = "1.0.0"
